### ISSUE TITLE
Using more linters

### ISSUE THREAD

**Issue by jonathantneal** [liferay/liferay-frontend-source-formatter#11]
I love that you’re using [ESLint](https://github.com/natecavanaugh/check-source-formatting/blob/v1.1.8/lib/eslint_config.js) to handle code conformance, but I see that it’s targeting correctness **and** [style conformity](https://github.com/natecavanaugh/check-source-formatting/blob/v1.1.8/lib/eslint_config.js#L166).

I recommend checking out [JSCS](http://jscs.info/). It’s a style linter that focuses on enforcing your _style guide_. It might be nice to separate error prevention and pattern conformity with styling.

There’s a lot a great tool for enforcing style conformity in CSS files. It’s called [StyleLint](http://stylelint.io/). It has hundreds of rules that define how you want CSS to look.

There are Atom and Sublime plugins for ESLint, JSCS, and StyleLint, so you can attack this from the IDE and/or the build process.

If you’re interested, I’ve also written `.eslintrc`, `.jscsrc`, and `.stylelintrc` files that should be close to the patterns you once taught me, if they aren’t exact. I could put those into a PR if you are interested.

**Comment by natecavanaugh** [comment]
Heya Jon,
Thanks for the issue :)
I have definitely wanted to have a better way of making a distinction between errors ("this is broken, don't do it"), warnings ("this looks broken, and/or could cause issues"), and style violations ("we like tabs, not spaces, your pull request won't get accepted, but the world won't end").

I will for sure check out StyleLint (hopefully it's as customizable as ESLint is as regards writing custom rules :)

For the .rc files, could you attach them to this ticket? That way you don't have to put them anywhere in particular, and since they're not being used, I can pull them down when I integrate the others.

(Though we do have our rules for eslint configured [here](https://github.com/natecavanaugh/check-source-formatting/blob/master/lib/eslint_config.js))

Thanks again for filing this :)

**Comment by wincent** [comment]
We're [going to be archiving this project](https://github.com/liferay/liferay-frontend-source-formatter/pull/58#issuecomment-687057235) so closing everything.
