### ISSUE TITLE
Unclear warning: "function declaration was used before it was defined"

### ISSUE THREAD

**Issue by protoEvangelion** [liferay/liferay-frontend-source-formatter#32]
When calling a function declaration before it was declared you get `"'function name' was used before it was defined"`

For example:

```js
console.log(hello());

function hello() {
  return 'Hi!';
}
```

This warning is unclear because it is **valid syntax** to use a function declaration below its call site. IMHO that is one of the benefits of using function declarations over function expressions. You can have your core application at the top of the file while declaring your functions at the bottom to keep things cleaner. This is especially useful when working in a **non JSX environment** where files like a `view.jsp` can easily become very large.

I could see why this warning would be thrown for a function expression as that is indeed an error.

If this is a stylistic decision then maybe something along the lines of "_Function declaration needs to be defined before call site_" would be more clear.

**Comment by natecavanaugh** [comment]
This is for sure just a stylistic decision, but it's one we feel is important. I agree that it's valid syntax, but we tend to find it harder to follow the logic when things are defined later in the file, or at random, so we standardize to define first, whether it's a function expression or declaration, then there's no question as to if it will work, and where to find the logic.

The error message comes from eslint, so while it's possible to change, chances are I'll leave it be for now, since changing it would require a special edge case exception.

I'll leave this open for now, in case you have any thoughts on it, but I'll probably close it soon just to tidy things up.

Let me know though if there are any issues you have with this decision :)

**Comment by protoEvangelion** [comment]
After reading [this](https://eslint.org/docs/rules/no-use-before-define) it makes sense why that would be confusing pre es6. Thanks for the clarification!
