### ISSUE TITLE
Integrate with Prettier

### ISSUE THREAD

**Issue by protoEvangelion** [liferay/liferay-frontend-source-formatter#33]
What would it take to integrate with [Prettier](https://prettier.io/) or achieve a prettier type functionality where code is formatted on save?

Do you think it would be more feasible to try to write this functionality from scratch ourselves?

The dev experience is absolutely amazing using prettier and increases efficiency significantly.

**Comment by natecavanaugh** [comment]
Heya Ryan,
I actually haven't researched that part yet (been buried with a pernicious bug in portal), but what do you mean formatted on save? Does Prettier watch the file system, so no matter where it's saved from, it's automatically saved (like a gulp watch type thing)?
Or is it a specific tool chain?

Since it's "an opinionated code formatter", I should look more into what those opinions are vs our settings and see if they're compatible with our current ESLint settings (and they custom rules we've created). It probably possible, I just don't know for sure yet.

We also could use something like gulp watch (or it's underlying system) to do something similar, but I'll do some more research. I'll leave this one open until I can give some more definitive answers :)

**Comment by protoEvangelion** [comment]
Great questions! I should have been more specific in that prettier is an npm package and I have a [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for my editor VS Code that uses a VS Code language server. The extension also works with ESLint here: https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L189

The more that I think about it, trying to integrate with prettier would probably not be feasible because they are primarily focused on JS.

Do you have any way to expose the equivalent of an `eslint --fix` from the Node API: https://eslint.org/docs/developer-guide/nodejs-api#linterverifyandfix?

If it is too much trouble to try to add that functionality to freemarker & jsp files maybe we can just start with JS files.

I am open to sending a PR for this if you think it is a valuable feature.

**Comment by natecavanaugh** [comment]
Thanks!
You can pass -i, and it will fix a lot, but I'm still working on the eslint fix option for the rules that are enabled.
But for a lot of rules it should try to fix most things (though they may be more focused on JSPs and CSS [with some JS rules as well] at the moment).

I understand the overall intent (I think), which is a way to watch the file system and have it auto fix rather than having to run the command. Would that be an accurate way of stating it?
I just want to make sure that whatever I end up implementing meets your needs (and of course, PRs always welcome :) !

**Comment by protoEvangelion** [comment]
Do you expose a Node API equivalent to `-i`?

Is there one area in the code where you are calling the eslint Node Api where I could take a look at implementing auto fix? Possibly here? https://github.com/liferay/liferay-frontend-source-formatter/blob/7761b214a6069228803da6ecfe16ce45f37eb916/lib/lint_js.js#L127

Yes, the overall intent is to watch the file system and auto fix on save. Do you think that would be better handled by gulp or an editor extension?

**Comment by natecavanaugh** [comment]
Hi Ryan,
Sorry for the long delay here, but basically, that is the right location for where the code is transformed through ESLint, but basically, where possible, I try to have every formatter transform the content, whether it's written to disk or not, but what determines that with the `-i` flag is in the [cli.js here](https://github.com/liferay/liferay-frontend-source-formatter/blob/master/lib/cli.js#L111)

Basically, if the `inlineEdit` flag is set on the CLI instance, all of the code will be written to the file after it's formatted (if it's different, of course).

One way you could create this instance would be to do something like this:

```javascript
var CLI = require('check-source-formatting').CLI;

var cli = new CLI({
flags: {inlineEdit: true},
args: ['file_1.js']
});

cli.init().then(function(){
// formatting/writing is finished....
})
```

Hopefully that is still helpful (and again, sorry for the delay).

**Comment by wincent** [comment]
Independently of the question about editor/IDE integration and format-on-save, can we discuss whether a large part of the functionality of this project could be replaced through delegation to Prettier?

Prettier is extremely widely used ([30k+ GitHub stars](https://github.com/prettier/prettier), [3.7m weekly NPM downloads](https://www.npmjs.com/package/prettier)), is [fairly configurable](https://prettier.io/docs/en/options.html), and has a bunch of [editor integrations](https://prettier.io/docs/en/editors.html) that could be leveraged. Being so heavily used and so actively developed, the tool is incredibly robust and many, many bugs have been flushed out. It also formats multiple file formats, including CSS, SCSS, JS, HTML, which are of interest on the front-end.

I'd suggest that the tool is so valuable that, even if it differs in some formatting opinions from our existing practices (and I'm not sure it does, just saying hypothetically), then it would probably be worth changing our patterns in order to access the value we'd get from incorporating Prettier.

**Comment by p2kmgcl** [comment]
I also suggested recently some improvements (#41 #42 #43) that could be easily added by using prettier.

**Comment by wincent** [comment]
Yeah, I just commented on one of those with a playground link: https://github.com/liferay/liferay-frontend-source-formatter/issues/42#issuecomment-469587572

**Comment by protoEvangelion** [comment]
@natecavanaugh Where would be the proper integration point for the [Prettier](https://www.npmjs.com/package/prettier) module if it handles these file types:

```
JavaScript, including ES2017
JSX
Angular
Vue
Flow
TypeScript
CSS, Less, and SCSS
HTML
JSON
GraphQL
Markdown, including GFM and MDX
YAML
```

To address your concern about Prettier conflicting with ESLint rules, there is a [plugin](https://github.com/prettier/eslint-config-prettier) that will turn off conflicting rules.

**_Could we also pass off the formatting to Prettier for <script> or <style> blocks in JSPs & FTLs?_**  

To integrate this with the CLI, we could add a `--use-prettier` flag & a `usePrettier` option for config files.

@wincent I am 100% with you. The fact that prettier is great at formatting only syntactical opinions it significantly increases developer productivity.

I have witnessed this personal, from members on my team, and have heard this sentiment echoed many times throughout the frontend community.

**Comment by natecavanaugh** [comment]
@protoEvangelion 
To answer your question, it depends a bit on how it works. For instance, if Prettier only allows you to format files, rather than content, we may need to think through some possibilities.
If they allow you to mutate content, and choose how/where to write it, that would be easier.

Here's a brief overview of how the tool currently works, both for posterity and so you guys can know generally what's going on under the hood.

The general principle for this tool is that you pass it a list of files as arguments. We go through the files, filter out invalid files (non-existent files, corrupt files, etc), and go and read the contents for each file.
The tool mainly handles coordinating the formatters. The formatters are basically what transform the content.
A formatter can specify what types of file extensions it can work on, so if the file comes in with an unsupported extension, it will skip it.

There are currently 3 main formatters (html, js, and css), and each of the formatters use a "rule iterator", which basically, in specific files, it goes line by line through the file, and applies certain regex transformations that might not be possible with other linters.

Inside of the CSS and JS formatters, there's a linting method where the content is passed to the appropriate linter (whether ESLint or StyleLint).

So, the questions are:
- Does prettier have a Node API that allows us to pass content in and get transformed content out?
- Does prettier have configuration options that might be weird when configured alongside ESLint?

> Could we also pass off the formatting to Prettier for <script> or <style> blocks in JSPs & FTLs?

In theory we could, but it's much more dangerous. You see, for script and style tags, we do a LOT of pre-processing to ensure that we're going to be able to pass valid JS or CSS over to the linter, especially because inside of the JSP files, a lot of scriptlets are intermingled all over the HTML. It might be possible to handle, but it might be a bit fragile for embedded blocks.

**Comment by wincent** [comment]
> Does prettier have a Node API that allows us to pass content in and get transformed content out?

[Yes](https://prettier.io/docs/en/api.html).

> Does prettier have configuration options that might be weird when configured alongside ESLint?

It's effectively a non-problem because the tools are "designed" to work together. You basically turn of all the ESLint rules that are concerned with formatting via the [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) preset. In this way, Prettier concerns itself with how things *look*, and ESLint concerns it self with how things *are*, semantically, and neither competes with the other.

FWIW, we are using the eslint-config-prettier preset in our our own [eslint-config-liferay](https://github.com/liferay/eslint-config-liferay) preset.

> in specific files, it goes line by line through the file, and applies certain regex transformations that might not be possible with other linters.

This is a big difference in architecture compared to Prettier, which operates at the AST level. Prettier effectively is *just* a printer for the AST so it basically *can't* produce broken output, save for very rare bugs. In other words, you wouldn't see something like https://github.com/liferay/liferay-frontend-source-formatter/issues/34 where a regex looking for "try" happened to match inside "_updateDataSetEntrykey" and broke the program.

**Comment by wincent** [comment]
Currently experimenting with Prettier in liferay-portal for JS and SCSS only: https://issues.liferay.com/browse/LPS-96376

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
