### ISSUE TITLE
Less verbose output

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-source-formatter#38]
Currently, output for `csf` is very verbose. This is particularly harmful when a lot of files are scanned and few errors (if any) are found....

```bash
File: src/main/resources/META-INF/resources/js/actions/actions.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/dialogs/SelectMappingDialog.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/dialogs/SelectMappingTypeDialog.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/edit_mode/DisabledAreaMask.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/edit_mode/DisabledAreaPopover.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/edit_mode/EditModeWrapper.es.js
    	No errors

File: src/main/resources/META-INF/resources/js/components/floating_toolbar/background_color/FloatingToolbarBackgroundColorPanel.es.js
    	No errors
```

It would be good to be able to skip the output if no errors are found, create some type of aggregated digest or maybe have different modes `--verbose`, `--polite`, `--silent`... ?

**Comment by bryceosterhaus** [comment]
The simplest solution, removing the output if no errors exist for the file, can be seen here in the [content-logger](https://github.com/bryceosterhaus/content-logger/commit/d37242fdc804776aa4cc126a3ed2c79b3a8e2bd8). Wasn't sure how we want to handle this since its a dependent package though.

If we want to add flags, we should nail down which flag does what. Personally, I'm not sure adding flags does much. Removing the output for files that are not erroring seems pretty sufficient for almost all use cases.
