### ISSUE TITLE
Convert to monorepo?

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-source-formatter#39]
Hey @natecavanaugh, I noticed there are quite a few packages that this depends on that are all related. Do you think it would make sense to move those packages over here and convert this to a lerna repo?

The packages I noticed were:
- [content-formatter](https://github.com/natecavanaugh/content-formatter)
- [content-logger](https://github.com/natecavanaugh/content-logger)
- [content-logger-handlebars-helpers](https://github.com/natecavanaugh/content-logger-handlebars-helpers)

Others I noticed but was less sure about:
- [roolz](https://github.com/natecavanaugh/roolz)
- [string-sub](https://github.com/natecavanaugh/string-sub)

Let me know what you think!

**Comment by natecavanaugh** [comment]
Heya Bryce,
This is a good question, but I'm not sure for only one reason: The reason I split them out in the first place was to reuse those components inside of https://github.com/natecavanaugh/convert-bootstrap-2-to-3
Convert bootstrap to 3 doesn't have as much usage, but it's still there (and I've been working on the 3-to-4 part for a while, but it may be time to just kind of leave it).

But the end goal was to allow those reusable pieces be reused for similar contexts (basically, the case we seem to repeat a lot on the CLI, which is the CLI file(s), operate on the content (transform/report), log the results of the operations.

I would say all of those (minus `string-sub`, that's really just a super simple broad util for string templating) fit into the same general category, so I would imagine that we could make those 4 into it's own lerna repo, but I'm not sure if this or `convert-bootstrap-2-to-3` should be included in it, since they're the two consumers, but ultimately have little to do with the 4 specifically.

What do you think?

**Comment by bryceosterhaus** [comment]
Ah that makes sense. I agree in that I think those 4 packages could be its own lerna repo and then the rest can be independent. At least packaging a few of those together will make it easier to work with.

**Comment by wincent** [comment]
We're [going to be archiving this project](https://github.com/liferay/liferay-frontend-source-formatter/pull/58#issuecomment-687057235) so closing everything.
