### ISSUE TITLE
Add VSCode extension

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#41]
Having a VSCode extension allowing linting files without running it from console would be fantastic.

I offer myself to develop this plugin, but first I wanted to say it here for the case someone else has some work on it.

**Comment by natecavanaugh** [comment]
If you haven't already, you may wish to look at the [Atom plugin](https://github.com/mthadley/linter-liferay) (I'm not sure how portable they are, but it might be enough to get started).

If you come up with anything, paste a link here and I'll add it to the readme :)

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
