### ISSUE TITLE
Force new line on HTML attributes when there are more than two properties (Soy, JSX)

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#42]
When there are more than two properties in a HTML tag we should force adding a new line between them, so the code is more readable:

Invalid
```
<form class="form form-sample" id={formId} method="POST">
  <input class="input input-minimal input-sample" placeholder="placeholder" type="text" value="sample">
</form>
```

Valid
```
<form
  class="form form-sample"
  id={formId}
  method="POST"
>
  <input
    class="input input-minimal input-sample"
    placeholder="placeholder"
    type="text"
    value="sample"
  >
</form>
```

**Comment by natecavanaugh** [comment]
We do enforce this, but it's incredibly subjective, because it's not really a programmatic enforcement. Basically, if it's easier to read with new lines, we opt to that, but otherwise, it can start to be pedantic when applied 100% of the time, ie.:

```
<input
    class="input"
    type="text"
/>
```
vs.
```
<input class="input" type="text" />
```

There's a certain wiggle room within each context that makes this one trickier to enforce, unless you have some ideas for heuristics to use?

**Comment by wincent** [comment]
FWIW, Prettier handles this very well. [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEATggCZyEAUqEhAtgJIkCU+wAOlPkXDOoZxQ5cuAHmp0h+MABsAhgGd5AXjZoatfONoBaebNoAHaXFWScJJcC2MAvpNo8AFhAuqACgHkAygBVTUAD5JERwoA3QYSS4ZBWVVUPCYfASI7VpQnFpZaWSw1L1DY39hfCNZMDhnaTJCFRAyiqqa4uEYAE8DODr4AA9IkCj8ADds9C7VAqMTAc58AHogqBE5rUWSriYAbkGuGxAAGhAIA1xoeWRQWUJCCAB3NyuEc5RZIYhzA5AAI0JygGseF4DOVQgBzZAwQhjQ6OGC0aQAdUcOHg8mBFS8TxROCGKLayHAik+oXk5Bgbl+oKyyFQ2VJhwAVvIegAhX5gAEwLz6OAAGVCcBpdLgjOZXjBxgAiugIPAhdJ6fUrqTCASvrIvnBpNpUNI7p8DIRQjAEeYYI5kAAOAAMh0NEFJCN+BgJhrgKqGgsOxAAjugcMQKbIqbJ5YrSekIVCRSB5BK4NLZYKkLSFTHIbIcNIwQBhCC0akoKDQL0gdCknwa56Q6EgGAa00kc3IAAsNhsQA):

```javascript
function render(formId) {
	return (
		<form class="form form-sample" id={formId} method="POST">
			<input
				class="input input-minimal input-sample"
				placeholder="placeholder"
				type="text"
				value="sample"
			/>
		</form>
	);
}
```

**Comment by p2kmgcl** [comment]
@natecavanaugh the rule I use normally (suggested long ago by @carloslancha) is using new line for more than two attributes. This usually works fine.

However, prettier could solve this better :smile:

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
