### ISSUE TITLE
Forcing on code block braces breaks indentation

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#48]
It tries to transform this:

```
   if (thing) {
      ...
   } else {
      ...
   }
```

into this:

```
   if (thing) {
     ...
   }
   else {
     ...
   }
```

but produces this:

```
   if (thing) {
     ...
   }
 else {
     ...
   }
```

**Comment by p2kmgcl** [comment]
#33 related

**Comment by wincent** [comment]
Another example of this [here](https://github.com/brianchandotcom/liferay-portal/pull/72606#issuecomment-489541718).

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
