### ISSUE TITLE
Force concrete formatting for long conditionals

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#49]
(Suggested by BChan)

This:

```
if (
  conditionA &&
  conditionB &&
  conditionC &&
  conditionD
) {
  ...
}
```

Should be formatted:

```
if (conditionA &&
  conditionB &&
  conditionC &&
  conditionD) {
  
  ...
}
```

**Comment by p2kmgcl** [comment]
#33 related

**Comment by wincent** [comment]
> #33 related

Maybe not in this case, because I don't think Prettier can be configured to produce that kind of result. It offers some options, but does describe itself as "opinionated", and this is one area where I think its opinions differ.

**Comment by p2kmgcl** [comment]
@wincent can't we at least modify the AST after it has being altered by prettier?

**Comment by wincent** [comment]
@p2kmgcl: AFAIK the only way to do that is to fork Prettier. It has [an API that you can call](https://prettier.io/docs/en/api.html), but you can only pass it the same limited set of options. By the time the function returns, you're back to having just a string and not an AST, which means you are back in the fragile world of regex-based transforms. I don't think Prettier provides a way of plugging in a new printer to go from AST-via-custom-logic-to-string.

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
