### ISSUE TITLE
Force function newline for each parameters

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#50]
(Suggested by BChan)

For function calls that require multiple lines, we should place each parameter in a new line:

Valid:
```
fn(a, b)
```

Valid:

```
fetch().then(
  () => {
  }
)
```

Valid:

```
doThings(
  a,
  () => {
  }
)
```

Invalid:
```
doThings(a, () => {
});
```

Invalid:

```
fetch().then(() => {
});
```

**Comment by p2kmgcl** [comment]
#33 related

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`.
