### ISSUE TITLE
Force newline between different "code blocks"

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#51]
We should separate different "code blocks" (variable declarations, assignments, loops, function calls...) with new lines:

Invalid:

```
let a = null;
b = 3;
if (things) {
}
fn(a, b)
```

Valid:

```
let a = null;

b = 3;

if (things) {
}

fn(a, b)
```

**Comment by wincent** [comment]
Some "prior art" can be found in ESLint which can detect and fix quite a few variants: https://eslint.org/docs/rules/padding-line-between-statements

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier/ESLint over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`; if this is something that we want to formalize we should create a new issue over in the [liferay-npm-tools](https://github.com/liferay/liferay-npm-tools) repo.
