### ISSUE TITLE
Provide linting for arrow function parens

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#52]
`eslint` allows defining when parentheses should/shouldn't be present in an arrow function: https://eslint.org/docs/rules/arrow-parens#as-needed

@jbalsas I think we agreed using parens only when needed, am I right?

**Comment by wincent** [comment]
Closing this because [liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/tree/master/packages/liferay-npm-scripts) is running Prettier over the JS files in [liferay-portal](https://github.com/liferay/liferay-portal) (and [soon over JSP too](https://github.com/liferay/liferay-npm-tools/issues/98)) and are no longer running `csf`. Prettier will add/remove arrow function parens as appropriate.
