### ISSUE TITLE
Force more consistent JSDoc typing

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-source-formatter#53]
Force using uppercase or lowercase in JSDoc primitive types, and disallow mixing box cases. This will improve documentation consistency

Invalid
```
/**
 * @param {object} a
 * @param {array} b
 * @param {Object} c
 * @param {Array} d
 * @param {Object[]} e
 * @param {Array<String>} f
 * ...
 */
```

Valid
```
/**
 * @param {Object} a
 * @param {Array} b
 * @param {Object} c
 * @param {Array} d
 * @param {Object[]} e
 * @param {Array<String>} f
 * ...
 */
```
or
```
/**
 * @param {object} a
 * @param {array} b
 * @param {object} c
 * @param {array} d
 * @param {object[]} e
 * @param {Array<string>} f
 * ...
 */
```

**Comment by wincent** [comment]
May also want to be consistent with [TypeScript's names for those types](https://www.typescriptlang.org/docs/handbook/basic-types.html), given that if we start using an actual type system in JS within portal it will TypeScript (and relatedly, that will obviate the need for a lot of these `@param` docs because they will already be documented in the code itself).

**Comment by wincent** [comment]
We're [going to be archiving this project](https://github.com/liferay/liferay-frontend-source-formatter/pull/58#issuecomment-687057235) so closing everything.
